# Generated by Django 5.2.11 on 2026-02-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GasReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reading_date', models.DateField(help_text='Дата снятия показания', unique=True, verbose_name='Дата')),
                ('reading_value', models.PositiveIntegerField(help_text='Показание на дату снятия', verbose_name='Показание')),
                ('reading_qty', models.PositiveIntegerField(help_text='Количество единиц', verbose_name='Потребление', blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Цена за единицу', max_digits=10, verbose_name='Цена')),
                ('trans_sum', models.DecimalField(decimal_places=2, help_text='Сумма за транспортировку (по умолчанию предыдущее значение)', max_digits=10, verbose_name='Транспортировка')),
            ],
            options={
                'verbose_name': 'показание газа',
                'verbose_name_plural': 'показания газа',
            },
        ),
    ]
