# Generated by Django 5.2.11 on 2026-02-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0001_gas_reading'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reading_date', models.DateField(help_text='Дата снятия показания', unique=True, verbose_name='Дата')),
                ('reading_value', models.PositiveIntegerField(help_text='Показание на дату снятия', verbose_name='Показание')),
                ('reading_qty', models.PositiveIntegerField(blank=True, help_text='Количество единиц', null=True, verbose_name='Потребление')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Цена за единицу', max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'показание электричества',
                'verbose_name_plural': 'показания электричества',
            },
        ),
    ]
