# Generated by Django 5.2.11 on 2026-02-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0002_elect_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='electreading',
            name='adj_unit_sum',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Корр. суммы', max_digits=10, verbose_name='Корр. суммы'),
        ),
        migrations.AddField(
            model_name='gasreading',
            name='adj_unit_sum',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Корр. суммы', max_digits=10, verbose_name='Корр. суммы'),
        ),
        migrations.AddField(
            model_name='gasreading',
            name='adj_trans_sum',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Сумма корректировки транспортировки (положительная — доплата, отрицательная — переплата)', max_digits=10, verbose_name='Корректировка транспортировки (UAH)'),
        ),
    ]
